name: ant_sports_flutter
description: K12 AI sports mobile app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.5.0+1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  socket_io_client: ^2.0.3+1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
